export const BusinessSector={
    TECHNOLOGY: "TECHNOLOGY",
    FINANCE: "FINANCE",
    HEALTHCARE:"HEALTHCARE",
    RETAIL:"RETAIL",
    MANUFACTURING:"MANUFACTURING",
    ENTERTAINMENT:"ENTERTAINMENT",
    EDUCATION:"EDUCATION",
    FOOD_AND_BEVERAGE:"FOOD_AND_BEVERAGE",
    REAL_ESTATE:"REAL_ESTATE",
    ENERGY:"ENERGY",
    TRANSPORTATION:"TRANSPORTATION",
    MEDIA:" MEDIA",
    AUTOMOTIVE:"AUTOMOTIVE",
    TELECOMMUNICATIONS:"TELECOMMUNICATIONS",
    TRAVEL_AND_TOURISM:"TRAVEL_AND_TOURISM",
    SPORTS:"SPORTS",
    OTHER:"OTHER",
}
export const ContactPreference={
    Email:"Email",
    Mobile:"Mobile",
    Web_Site:"Web_Site",

}
export  const ClientType={
    INDIVIDUAL:"INDIVIDUAL",
    COMPANY:"COMPANY",
}
export default {BusinessSector,ClientType,ContactPreference};